spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: admin
    initialization-mode: always
    schema: classpath:/dev/data.sql